### ISSUE TITLE
Any examples of metered billing?

### ISSUE THREAD

**Issue by zspine** [hiqdev/php-billing#6]
Hi!

I am in the process of implementing a billing system on a symfony 4 based application and I found this library to be very interesting and almost looks like I do not have to reinvent the wheel again. In any case I could not find any useful examples or documentation in English or Russian? Even I checked the behat features and coundn't find anything to follow along....

Do you have any example use case for metered billing?

Any suggestion or help greatly appreciated! Thank you!

**Comment by SilverFire** [comment]
Hello, @zspine!

Indeed, this billing is designed to be flexible and abstract, so supports different use cases. We use this package in production, wrapping it additional layers, such as: 

1. `Plan` and `Price` storage and management UI for managers, so they can create plans, fill them with prices and assign to `Customers`.
2. Actions and Orders producer. This layer takes end-user actions (such as purchasing something) and produces the right `Action`s inside the `Order`
3. Persistence layer. This layer implements various RepositoryInterfaces, defined in this package (such as [PlanRepositoryInterface](https://github.com/hiqdev/php-billing/blob/master/src/plan/PlanRepositoryInterface.php), providing data saving and retrieving logic for the required entities.
4. Periodic operations (CRON tasks). This includes meters fetching (such as accumulated resources consumption), transforming them to actions with the right quantity, running billing on them, updating Bills and their Charges.
5. Business metrics monitoring, analysis and alerting. This layer provides regular checks over data, produces by the billing in order to ensure system health.
6. Read API. This API accepts requests, fetches data from the DBMS and implements search with filtering, ordering, access control and more for Orders, Actions, Bills, Prices and so on.

So, as you can see, this package is a concrete foundation of big billing system, but it requires a lot of bricks on top of it to become a fully operable billing. Unfortunately, we do not have all those bricks open-sourced and documented because many of them implement customer-specific logic that cannot be disclosed. 

We were thinking about making clear documentation at least for this package, explaining what kind of bricks it requires to become a fully-working billing system and how to make glue them together, but we don't have such for now.

**Comment by zspine** [comment]
Hi @SilverFire 

Thank you very much for the detailed response. Yes, I checked in to the code base and I understood that it's the base layer and not tied to any orm or framework. So still I believe it's a big time saver even though there are no much helpful documents to follow. Your explanation is helpful enough to understand the code.

Yes it would be great if you could put some cleaner documentation. Something similar to [sylius examples](https://docs.sylius.com/en/1.4/components_and_bundles/components/Order/basic_usage.html) also would be helpful enough than writing lots of content.....

Keep up the excellent work, Cheers!

**Comment by hiqsol** [comment]
Copied this "disclosure" to README.
